### ISSUE TITLE
DeluxeChat compatibility

### ISSUE THREAD

**Issue by V3x1Dev** [AuraDevelopmentTeam/BungeeChat2#100]
#### Issue Description: 
Bungeechat overides DeluxeChat's formatting

#### What happens:
When using Bungeechat and deluxe chat on the same network bungeechat overides my chat formating 

#### What you expected to happen:

I am mainly using Bungeechat for staff chat and other global messaging. And am using deluxechat to format the chat.

#### Steps to reproduce:

1. Install Bungeechat on Bungee server
2. Install DeluxeChat on backend spigot server
3. Start server 
...

____
#### Affected Versions: 

- Minecraft: 1.14.4
- BungeeChat:  v2.1.6
- Other related plugins: DeluxeChat v1.15.0

**Comment by V3x1Dev** [comment]
.

**Comment by BrainStone** [comment]
My apologies. I saw that issue but forgot about it because I was stressed.

Anyways it's expected that BungeeChat overrides your backend chat plugins. Because BungeeChat is not a chat relay plugin but a chat plugin.

Now if you want to use DeluxeChat for the local chats, the enable `passToClientServer` for local chat and set the local chat format to an empty message.

**Comment by V3x1Dev** [comment]
That's alright thanks I appreciate the response. Also it worked.
