### ISSUE TITLE
passToClientServer triple messages

### ISSUE THREAD

**Issue by Behoston** [AuraDevelopmentTeam/BungeeChat2#11]
Hi, I want to setup chat on my network like in  multichat plugin:
default global chat, local on demand plus passing messages to servers (to works with denizen). But if I enable local, global and pass to servers I got 3 messages (global, then local, then server). I want to see it once. How it can be done?

**Comment by BrainStone** [comment]
First of all, when you want to have Global and Local Chat and being able to toggle between the two, enable both and be sure to have the Global Chat set to false.
Then to disable the chat from the Spigot, you need to have a chat plugin installed there and set the format to something empty so that nothing will send.

**Comment by BrainStone** [comment]
@Behoston I'm going to close this issue. If you have question, feel free to ask.
