### ISSUE TITLE
Feature: Placeholders to work with Towny chat

### ISSUE THREAD

**Issue by carolusFPV** [AuraDevelopmentTeam/BungeeChat2#171]
It would be nice to be able to see nation and town in chat like what you would normally see, maybe with placeholders?
Or just an option to show chat like how the server would normally show it, but pipe it to the whole network.

**Comment by AwesomestCode** [comment]
I believe both of these requests are impossible to accomplish. For the first one, we would have to connect to a plugin on the Spigot server. This is not possible since we are a BungeeCord plugin, not a Spigot one. However, a bridge which may make this possible is planned to be implemented in BungeeChat 3. For the second one, BungeeChat is not a chat relay plugin, nor is it possible to accurately implement such functionality—the only way to do that would to be intercepting messages from a player on the origin server and mirror that to all other players, possibly relaying player specific messages in the process.
