### ISSUE TITLE
Feature Request: Respect LuckPerms Contexts

### ISSUE THREAD

**Issue by xtechgamer735** [AuraDevelopmentTeam/BungeeChat2#20]
Hello!

Moved to BungeeChat from MultiChat and immediately started feeling the benefits! However, one thing  I have noticed is that sadly the contexts of the player are not respected in chat.

For example, chat prefix must be set to the global context for it to be applied when a player meets the context.

I do hope this can be added!

Many thanks,

**Comment by dustinduse** [comment]
The reasoning for this, is that bungeecord is considered part of the global context. So until there is a way to register new prefixes and gather info from servers I believe this issue will remain open. I recently told Brainstone I would work on such a system as an addon. So if this is something you are looking for as well I'd be happy to link when it's done.

**Comment by xtechgamer735** [comment]
Yeah that would be great thanks! Do you know when this might be done? Just that my entire chat/prefix system is messed up and I'm not really sure how to fix it haha.

**Comment by BrainStone** [comment]
Bungee Chat does respect the context. However it is the context on the bungee. As long as you are only dealing with per server roles/prefixes you can do the following:

Instead of using `/lp ... server=<server>` use `/lp ... server=bungee world=<server>` in addition.
You can also run `/lpb user <you> info` to display the contexts you have on the bungee.

------------------------------------------------------------

I'm planning on making a bridge for Bungee Chat to allow to get local contexts and more.
